webfun/rails/ZombieTwitter/config/routes.rb
ZombieTweets::Application.routes.draw do
  root :to => "zombies#index"
  resources :zombies do
    resources :tweets, :weapons 
  end

  resources :tweets
end

webfun/rails/ZombieTwitter/app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :category
end

webfun/rails/ZombieTwitter/app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :tweet, :dependent => :destroy
end

webfun/rails/ZombieTwitter/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :zombie
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_one :location

  before_save :check_location
  before_save :set_show_location

  after_update {|tweet| logger.info "Tweet #{tweet.id} updated" }
  after_destroy {|tweet| logger.info "Tweet #{tweet.id} deleted" }

  scope :recent, order('created_at desc').limit(4)
  scope :graveyard, where(show_location: true, location: {name:'graveyard'})

  validates :message, presence: true

  accepts_nested_attributes_for :location

  private

  def check_location 
    if self.location
      self.show_location = true
    end
  end

  def set_show_location 
    self.show_location = location
  end
end

webfun/rails/ZombieTwitter/app/models/weapon.rb
class Weapon < ActiveRecord::Base
  has_and_belongs_to_many :zombies
  before_save :check_ammo

  CONDITIONS = ["New", "Rusty", "Broken"]

  def toggle_condition
    c_index = CONDITIONS.find_index(self.condition)
    self.condition = CONDITIONS[c_index - 1] 
    self.save
  end

  private
  def check_ammo 
    if ammo == 3
      WeaponMailer.low_ammo(@user).deliver 
    end
  end
end

webfun/rails/ZombieTwitter/app/models/zombie.rb
 class Zombie < ActiveRecord::Base
  has_many :tweets
  has_and_belongs_to_many :weapons

  def as_json(options)
    super(options || {only: [:name, :ammo], include: :weapons})
  end
end

webfun/rails/ZombieTwitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

webfun/rails/ZombieTwitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    if params[:zombie_id]
      @tweets = Tweet.recent.includes(:location).where(zombie_id: params[:zombie_id])
    else
      @tweets = Tweet.recent.includes(:location)
    end
    @graveyard_tweets = Tweet.recent.graveyard

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @zombie = Zombie.find(params[:zombie_id])
    @tweet = Tweet.new
    @tweet.location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @zombie = Zombie.find(params[:zombie_id])
    location = params[:tweet].delete :location
    @tweet = @zombie.tweets.new(params[:tweet])
    @tweet.build_location(location)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render json: @tweet, status: :created, location: @tweet }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])
    binding.pry
    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :ok }
    end
  end
end

webfun/rails/ZombieTwitter/app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  def index
    @zombie = Zombie.find(params[:zombie_id]) 
    @weapons = @zombie.weapons
  end

  def show
    @zombie = Zombie.find(params[:zombie_id]) 
    @weapon = @zombie.weapons.find(params[:id])
    render json: @weapon.to_json(except: [:id, :created_at, :updated_at, :email], include: :zombie)
  end

  def create
    @weapon = Weapon.new(params[:post]) 
    if @weapon.save
      render json: @weapon, status: :created, location: @weapon 
    else
      render json: @weapon.errors, status: :unprocessable_entity 
    end
  end

  def fire_weapon
    @weapon = Weapon.find(params[:id]) 
    @weapon.fire!
    if @weapon.low_ammo?
      render :fire_and_reload 
    end
  end

  def reload
    @weapon = Weapon.find(params[:id]) respond_to do |format|
    if @weapon.ammo < 30
      @weapon.reload(params[:ammo_to_reload])
      format.json { render :json => @weapon.to_json(:only => :ammo), status: :ok } 
      format.html { redirect_to @weapon, notice: 'Weapon ammo reloaded' }
    else
      format.json { render :json => @weapon.to_json(:only => :ammo), status: :unprocessable_entity }
      format.html { redirect_to @weapon, notice: 'Weapon not reloaded' }
    end
    format.js
  end

  def toggle_condition
    @weapon = Weapon.find(params[:id]) 
    @weapon.toggle_condition 
    respond_to do |format|
      format.html { redirect_to @weapon, notice: 'Changed condition' }
      format.js 
    end
  end
end

webfun/rails/ZombieTwitter/app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  respond_to :html

  def index
    @zombies = Zombie.all  
  end

  def new
    @zombie = Zombie.new
  end

  def create
    @zombie = Zombie.new(params[:zombie])
    @zombie.save
    respond_with @zombie
  end

  def show
    @zombie = Zombie.find(params[:id])
  end
end

webfun/rails/ZombieTwitter/app/helpers/application_helper.rb
module ApplicationHelper
end

webfun/rails/ZombieTwitter/app/helpers/tweets_helper.rb
module TweetsHelper
end

webfun/rails/ZombieTwitter/app/helpers/weapons_helper.rb
module WeaponsHelper
end

webfun/rails/ZombieTwitter/app/helpers/zombies_helper.rb
module ZombiesHelper
end

webfun/rails/ZombieTwitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZombieTweets</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

webfun/rails/ZombieTwitter/app/views/tweets/_form.html.erb
<%= form_for([@zombie, @tweet]) do |f| %>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.fields_for :location do |l| %>
      <%= l.label :name, :location %><br />
      <%= l.text_field :name %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webfun/rails/ZombieTwitter/app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

webfun/rails/ZombieTwitter/app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Zombie</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.message %></td>
    <td><%= tweet.zombie.name %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<% unless params[:zombie_id] %>
  <p><%= link_to "Back to Zombies", zombies_path %></p>
<% end %>

webfun/rails/ZombieTwitter/app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', zombie_tweets_path(@zombie) %>

webfun/rails/ZombieTwitter/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @tweet.message %>
</p>

<p>
  <b>Zombie:</b>
  <%= @tweet.zombie.name %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> | <%= link_to 'Delete', tweet_path(@tweet),confirm: 'Are you sure?', method: :delete %>

<p><%= link_to "Back to Tweets", tweets_path %></p>

webfun/rails/ZombieTwitter/app/views/weapons/_form.html.erb
<%= form_for([@user, @weapon]) do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :ammo %>
  <%= f.select :condition, ["New", "Rusty", "Broken"] %>
  <%= f.date_select :purchased_on %>
<% end %>

webfun/rails/ZombieTwitter/app/views/weapons/index.html.erb
<h2><%= @zombie.name %>'s weapons</h2>
<ul>
<% @weapons.each do |w| %>
  <li><%= link_to w.name, [@zombie, w] %></li>
<% end %>
</ul>
<%= link_to "New Weapon", new_user_weapon_path(@user) %>

webfun/rails/ZombieTwitter/app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>
<ul> 
  <li>
    <em>Name:</em>
    <%= @weapon.name %>
  </li>
  <li>
    <em>Condition:</em>
    <span id="condition"><%= @weapon.condition %></span>
    <%= link_to "Toggle", toggle_condition_weapon_path(@weapon), remote: true %>
  </li> 
  <li>
    <em>Ammo:</em>
    <span id="ammo"><%= @weapon.ammo %></span>
  </li>
</ul>

<%= form_for @weapon, url: reload_weapon_path(@weapon), remote: true do |f| %> 
  <div class="field">
    Number of bullets to reload:
    <%= number_field_tag :ammo_to_reload, 30 %> 
    <br /> 
    <%= f.submit "Reload" %>
  </div>
<% end %>

webfun/rails/ZombieTwitter/app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

webfun/rails/ZombieTwitter/app/views/zombies/_weapon.html.erb
<%= div_for weapon do %>
  <h2><%= weapon.name %></h2> 
  <p>
    Condition: <%= weapon.condition %>
    Ammo: <%= weapon.ammo %>
    Purchased <%= time_ago_in_words weapon.purchased_on %> ago
  </p> 
<% end %>

webfun/rails/ZombieTwitter/app/views/zombies/index.html.erb
<h1>Zombies</h1>
<ul>
  <% @zombies.each do |zombie| %>
    <li><%= link_to zombie.name, zombie %></li>
  <% end %>
</ul>
<%= link_to "New zombie", new_zombie_path %>
  

webfun/rails/ZombieTwitter/app/views/zombies/new.html.erb
<h1>New Zombie</h1>
<%= render "form" %>

webfun/rails/ZombieTwitter/app/views/zombies/show.html.erb
<h1><%= @zombie.name.titleize %></h1>

<%= render @zombie.weapons %>

<p><%= pluralize(@zombie.tweets.size, "Tweet") %></p> 

<p><%= link_to "Create a new Tweet for #{@zombie.name}", new_zombie_tweet_path(@zombie) %></p>
<p><%= link_to "Back to Zombies", zombies_path %></p>